use super::*;

impl PetriApp {
    #[cfg(test)]
    pub(in crate::ui::app) fn new_for_tests() -> Self {
        let mut net = PetriNet::new();
        net.set_counts(2, 1);
        net.places[0].pos = [120.0, 150.0];
        net.places[1].pos = [340.0, 150.0];
        net.transitions[0].pos = [240.0, 145.0];

        Self {
            net,
            tool: Tool::Edit,
            canvas: CanvasState::default(),
            sim_params: SimulationParams::default(),
            sim_result: None,
            show_sim_params: false,
            show_results: false,
            show_atf: false,
            atf_selected_place: 0,
            atf_text: String::new(),
            file_path: None,
            last_error: None,
            layout_mode: LayoutMode::TileVertical,
            show_graph_view: true,
            show_table_view: false,
            table_fullscreen: false,
            table_panel_width: 420.0,
            place_props_id: None,
            transition_props_id: None,
            show_place_props: false,
            show_transition_props: false,
            text_props_id: None,
            show_text_props: false,
            arc_props_id: None,
            show_arc_props: false,
            show_debug: false,
            debug_step: 0,
            debug_playing: false,
            debug_interval_ms: 1000,
            debug_arc_animation: true,
            debug_animation_enabled: false,
            debug_animation_local_clock: 0.0,
            debug_animation_current_duration: 0.0,
            debug_animation_last_update: None,
            debug_animation_events: Vec::new(),
            debug_animation_active_event: None,
            debug_animation_step_active: false,
            debug_place_colors: Vec::new(),
            show_proof: false,
            text_blocks: Vec::new(),
            next_text_id: 1,
            decorative_frames: Vec::new(),
            next_frame_id: 1,
            clipboard: None,
            paste_serial: 0,
            undo_stack: Vec::new(),
            legacy_export_hints: None,
            status_hint: None,
            show_help_development: false,
            show_help_controls: false,
            place_stats_dialog_place_id: None,
            place_stats_dialog_backup: None,
            show_place_stats_window: false,
            place_stats_view_place: 0,
            place_stats_series: PlaceStatsSeries::Total,
            place_stats_zoom_x: 1.0,
            place_stats_pan_x: 1.0,
            place_stats_show_grid: true,
            arc_display_mode: ArcDisplayMode::All,
            arc_display_color: NodeColor::Default,
            show_netstar_export_validation: false,
            pending_netstar_export_path: None,
            netstar_export_validation: None,
            show_new_element_props: false,
            show_markov_window: false,
            markov_model_enabled: false,
            markov_model: None,
            markov_model_pending_compute: false,
            sim_run_serial: 0,
            markov_computed_for_sim_serial: None,
            markov_recompute_attempts: 0,
            markov_limit_reached: false,
            markov_annotations: HashMap::new(),
            markov_place_arcs: Vec::new(),
            markov_arc_view_mode: MarkovArcViewMode::AggregatedWeighted,
            selected_markov_arc: None,
            markov_stationary_row_offsets: Vec::new(),
            markov_state_graph_row_offsets: Vec::new(),
            new_place_size: VisualSize::Medium,
            new_place_color: NodeColor::Default,
            new_place_marking: 0,
            new_place_capacity: Some(1),
            new_place_delay: 0.0,
            new_transition_size: VisualSize::Medium,
            new_transition_color: NodeColor::Default,
            new_transition_priority: 1,
            new_arc_weight: 1,
            new_arc_color: NodeColor::Default,
            new_arc_inhibitor: false,
            new_arc_inhibitor_threshold: 1,
            new_element_props_window_size: Vec2::new(360.0, 520.0),
            new_element_props_window_was_open: false,
        }
    }
}
